version: '3.9'

services:
  rupiyal-api-service:
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
    networks:
      - rupiyal-service-network
  db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rupiyal_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rupiyal-service-network
    expose:
      - 5432

volumes:
  pgdata: { }

networks:
  rupiyal-service-network: