spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/rupiyal_db
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    baseline-description: "init"
    baseline-version: 0


currency-rates-api:
  api-url: https://script.google.com/macros/s/AKfycbzuAOesxVUTL9xrVpAQVq5txvYWuHl2bLrtrI3cG95oPO2y0svIRl8krXznvdL7zy_2Ug/exec
  read-timeout: 10000
  connect-timeout: 10000