apiVersion: 0.0.1
kind: ComponentConfig
spec:
  inbound:
    - name: rupiyal-api-service
      port: 8080
      type: REST
      networkVisibility: Organization
      context: /
      schemaFilePath: openapi.yaml